import '@/styles/globals.scss';
import { AuthenticationProvider } from '@/context/authentication';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthenticationProvider>
        <body>
          <ToastContainer />
          {children}
        </body>
      </AuthenticationProvider>
    </html>
  );
}
