# Generated by Django 3.2.8 on 2023-07-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_active_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
