# Generated by Django 3.2.8 on 2023-07-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sociallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='url',
            new_name='social_link',
        ),
    ]
